In [1]:
import tensorflow as tf
import numpy as np
from LorisNet import *

In [2]:
inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(3, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(3, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3)]               0         
                                                                 
 dense (Dense)               (None, 3)                 12        
                                                                 
 dense_1 (Dense)             (None, 3)                 12        
                                                                 
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])
model(np.random.random((2, 3)))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.19554374, 0.24872524, 0.555731  ],
       [0.31460282, 0.35510442, 0.33029273]], dtype=float32)>

In [5]:
inputs = tf.keras.Input(shape=(3,))
_dense_kwargs = {'activation': tf.nn.relu}
outputs = MLPWithSkipConnections(2,
                                 3,
                                 .1,
                                 _dense_kwargs=_dense_kwargs)(inputs)
#outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [6]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 3)]               0         
                                                                 
 mlp_with_skip_connections (  (None, 9)                24        
 MLPWithSkipConnections)                                         
                                                                 
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])
model(np.random.random((2, 3)))

<tf.Tensor: shape=(2, 9), dtype=float32, numpy=
array([[0.64547074, 0.7611397 , 0.370337  , 1.3070933 , 0.        ,
        0.7987033 , 0.        , 0.        , 1.5905092 ],
       [0.9865214 , 0.8733666 , 0.3540978 , 1.7362329 , 0.        ,
        0.9626336 , 0.        , 0.        , 2.0252023 ]], dtype=float32)>