In [1]:
import tensorflow as tf
import numpy as np
from LorisNet import *

In [2]:
inputs = tf.keras.Input(shape=(3,))
outputs =MultiAttentiveTransformerNoFeedback(number_masks=200,
                                             dropout_rate=.1,
                                             dim_reduction=.7,
                                             activity_regularizer=tf.keras.regularizers.L2(),
                                             kernel_regularizer=tf.keras.regularizers.L2(),
                                             MLP_with_skip_connections_depth=4)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3)]               0         
                                                                 
 multi_attentive_transformer  (None, 200, 3)           2508      
 _no_feedback (MultiAttentiv                                     
 eTransformerNoFeedback)                                         
                                                                 
Total params: 2,508
Trainable params: 2,508
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])
model(np.random.random((2, 3)))

<tf.Tensor: shape=(2, 200, 3), dtype=float32, numpy=
array([[[0.329775  , 0.329775  , 0.34044996],
        [0.33111957, 0.33776087, 0.33111957],
        [0.32681325, 0.34637347, 0.32681325],
        ...,
        [0.33960992, 0.33465904, 0.32573107],
        [0.33286995, 0.33929083, 0.32783923],
        [0.33979037, 0.3299689 , 0.3302407 ]],

       [[0.33036757, 0.33036757, 0.33926487],
        [0.33148822, 0.3370236 , 0.33148822],
        [0.327899  , 0.34420198, 0.327899  ],
        ...,
        [0.3385647 , 0.33443826, 0.326997  ],
        [0.3329471 , 0.33829877, 0.32875413],
        [0.33871514, 0.33052915, 0.33075568]]], dtype=float32)>

In [5]:
model = tf.keras.Sequential()
model.add(MultiAttentiveTransformerWithFeedback(number_masks=200,
                                                dropout_rate=.1,
                                                dim_reduction=.7,
                                                activity_regularizer=tf.keras.regularizers.L2(),
                                                kernel_regularizer=tf.keras.regularizers.L2(),
                                                MLP_with_skip_connections_depth=4))

In [6]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])

In [7]:
model([np.random.random((2, 3)),
       [np.random.random((2, 3)), np.random.random((2, 3))],
       [np.random.random((2, 200, 3)), np.random.random((2, 200, 3))]])

array([[0.75705128, 0.32457966, 0.19960554],
       [0.56621285, 0.82089675, 0.14060158]])>, [<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.51621188, 0.24747799, 0.94734509],
       [0.20429389, 0.53197428, 0.73202192]])>, <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.37192694, 0.8761068 , 0.16233312],
       [0.77332109, 0.21870508, 0.01823215]])>], [<tf.Tensor: shape=(2, 200, 3), dtype=float64, numpy=
array([[[0.99269463, 0.3027317 , 0.27884096],
        [0.24704029, 0.87578147, 0.74124284],
        [0.35407162, 0.73907646, 0.72251857],
        ...,
        [0.0026337 , 0.30741203, 0.85187796],
        [0.28362275, 0.29162249, 0.16090117],
        [0.96993409, 0.20980187, 0.21656335]],

       [[0.11484539, 0.79539671, 0.32211081],
        [0.40347322, 0.75092041, 0.87457058],
        [0.28195052, 0.56626436, 0.95568768],
        ...,
        [0.13264283, 0.68004208, 0.0321692 ],
        [0.48458914, 0.11229766, 0.42282788],
        [0.28511721, 0.39418729, 0.

<tf.Tensor: shape=(2, 200, 3), dtype=float32, numpy=
array([[[0.33333334, 0.33333334, 0.33333334],
        [0.33333334, 0.33333334, 0.33333334],
        [0.33333334, 0.33333334, 0.33333334],
        ...,
        [0.33333334, 0.33333334, 0.33333334],
        [0.33333334, 0.33333334, 0.33333334],
        [0.33333334, 0.33333334, 0.33333334]],

       [[0.3332167 , 0.33353028, 0.33325297],
        [0.33233997, 0.33394086, 0.33371913],
        [0.3322716 , 0.33386543, 0.3338629 ],
        ...,
        [0.33449805, 0.33171067, 0.33379126],
        [0.33220214, 0.33220214, 0.3355957 ],
        [0.33341178, 0.33194834, 0.3346399 ]]], dtype=float32)>