In [1]:
import tensorflow as tf
from LorisNet import *

In [2]:
inputs = tf.keras.Input(shape=(10,))
outputs = StepNoFeedback(output_units=4,
                         pass_next_step_units=4,
                         multi_attentive_transformer=MultiAttentiveTransformerNoFeedback(number_masks=200,
                                                                                         dropout_rate=.1,
                                                                                         dim_reduction=.7,
                                                                                         activity_regularizer=tf.keras.regularizers.L2(),
                                                                                         kernel_regularizer=tf.keras.regularizers.L2(),
                                                                                         MLP_with_skip_connections_depth=4),
                         dropout_rate=.1,
                         dim_reduction=.7,
                         kernel_regularizer=tf.keras.regularizers.L2(),
                         number_parallel_groups=-1,
                         MLP_with_skip_connections_depth=4)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10)]              0         
                                                                 
 step_no_feedback (StepNoFee  ((None, 4),              35242     
 dback)                       (None, 4),                         
                              (None, 200, 10))                   
                                                                 
Total params: 35,242
Trainable params: 35,242
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])
model(np.random.random((2, 10)))

(<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0.03613378, 0.        , 0.        , 0.0093169 ],
        [0.01782341, 0.        , 0.        , 0.00269992]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[0.03771443, 0.        , 0.        , 0.11569746],
        [0.04796218, 0.        , 0.        , 0.10935685]], dtype=float32)>,
 <tf.Tensor: shape=(2, 200, 10), dtype=float32, numpy=
 array([[[0.06361902, 0.07414654, 0.12321366, ..., 0.1203749 ,
          0.13788806, 0.06361902],
         [0.08943583, 0.1012719 , 0.13834485, ..., 0.11645249,
          0.08943583, 0.10056968],
         [0.1362587 , 0.10796051, 0.0807227 , ..., 0.08165183,
          0.0807227 , 0.11561189],
         ...,
         [0.13405399, 0.08469159, 0.08469159, ..., 0.08469159,
          0.11760412, 0.09006165],
         [0.12291685, 0.11274119, 0.08017673, ..., 0.08017673,
          0.12995063, 0.08017673],
         [0.1171927 , 0.12496433, 0.08343989, ..., 0.09164654,
          0.

In [2]:
model = tf.keras.Sequential()
model.add(StepWithFeedback(output_units=4,
                           pass_next_step_units=4,
                           multi_attentive_transformer=MultiAttentiveTransformerWithFeedback(number_masks=200,
                                                                                             dropout_rate=.1,
                                                                                             dim_reduction=.7,
                                                                                             activity_regularizer=tf.keras.regularizers.L2(),
                                                                                             kernel_regularizer=tf.keras.regularizers.L2(),
                                                                                             MLP_with_skip_connections_depth=4),
                           dropout_rate=.1,
                           dim_reduction=.7,
                           kernel_regularizer=tf.keras.regularizers.L2(),
                           number_parallel_groups=-1,
                           MLP_with_skip_connections_depth=4))

In [3]:
model.compile(optimizer="Adam", loss="mse", metrics=["mae"])

In [4]:
model([np.random.random((2, 3)),
       [np.random.random((2, 3)), np.random.random((2, 3))],
       [np.random.random((2, 200, 3)), np.random.random((2, 200, 3))]])

array([[0.15529767, 0.32587362, 0.81448392],
       [0.0511035 , 0.87745967, 0.33894725]])>, [<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.42430116, 0.00679294, 0.33647578],
       [0.45424408, 0.75467447, 0.71329754]])>, <tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.58186359, 0.0450281 , 0.50061712],
       [0.98530185, 0.80884978, 0.1039414 ]])>], [<tf.Tensor: shape=(2, 200, 3), dtype=float64, numpy=
array([[[0.69399603, 0.57576721, 0.49958763],
        [0.77697491, 0.54757636, 0.887508  ],
        [0.43569136, 0.81245335, 0.96371968],
        ...,
        [0.8285406 , 0.86597051, 0.52945155],
        [0.91716542, 0.5099471 , 0.84920763],
        [0.32563817, 0.8493623 , 0.83119904]],

       [[0.60173395, 0.87147416, 0.84231533],
        [0.20772246, 0.66328437, 0.07506682],
        [0.11424936, 0.39055347, 0.43943083],
        ...,
        [0.95104539, 0.88647721, 0.69574018],
        [0.44730765, 0.32826391, 0.42969718],
        [0.66888596, 0.22576243, 0.

ValueError: Exception encountered when calling layer "sequential" (type Sequential).

All layers in a Sequential model should have a single output tensor. For multi-output layers, use the functional API.

Call arguments received by layer "sequential" (type Sequential):
  • inputs=['tf.Tensor(shape=(2, 3), dtype=float64)', ['tf.Tensor(shape=(2, 3), dtype=float64)', 'tf.Tensor(shape=(2, 3), dtype=float64)'], ['tf.Tensor(shape=(2, 200, 3), dtype=float64)', 'tf.Tensor(shape=(2, 200, 3), dtype=float64)']]
  • training=None
  • mask=None

In [5]:
import numpy as np

In [13]:
d = {'a': np.array,
    'b': [1, 2],
    'c': 3,
    'd': 4}

In [10]:
d.pop('a')(d.pop('b'))

array([1, 2])

In [14]:
[d.pop('a')(d.pop('b')), d.keys()]

[array([1, 2]), dict_keys(['c', 'd'])]